import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../models/berean_evaluation_model.dart';
import '../../../shared/services/pdf_formatter.dart';

class BereanPdfService {
  static Future<String> exportEvaluation(
    BereanEvaluationModel evaluation,
  ) async {
    final pdf = pw.Document();

    final verseColor = PdfColor.fromHex('#1E88E5');

    final headerStyle = pw.TextStyle(
      fontSize: 22,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromHex('#673AB7'),
    );
    final sectionTitleStyle = pw.TextStyle(
      fontSize: 16,
      fontWeight: pw.FontWeight.bold,
      color: PdfColor.fromHex('#673AB7'),
    );
    final bodyStyle = const pw.TextStyle(fontSize: 12, lineSpacing: 4);
    final bulletStyle = const pw.TextStyle(fontSize: 12, lineSpacing: 4);
    final italicStyle = pw.TextStyle(
      fontSize: 12,
      fontStyle: pw.FontStyle.italic,
      lineSpacing: 4,
    );
    final labelStyle = pw.TextStyle(
      fontSize: 11,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.grey700,
    );

    List<pw.Widget> buildParagraphs(String text) {
      if (text.isEmpty) return [];
      return PdfFormatter.formatMarkdown(
        PdfFormatter.cleanText(text),
        titleStyle: headerStyle,
        headingStyle: sectionTitleStyle,
        bodyStyle: bodyStyle,
        bulletStyle: bulletStyle,
        verseColor: verseColor,
      );
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) {
          return [
            pw.Text('Berean Check Evaluation', style: headerStyle),
            pw.SizedBox(height: 20),

            // Statement
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('STATEMENT ANALYZED', style: labelStyle),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    '"${evaluation.statement}"',
                    style: italicStyle.copyWith(fontSize: 14),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Verdict
            pw.Text(
              'VERDICT: ${evaluation.alignmentVerdict.label.toUpperCase()}',
              style: sectionTitleStyle.copyWith(
                color: PdfColor.fromHex('#e05c5c'),
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              evaluation.alignmentVerdict.oneLineVerdict,
              style: bodyStyle,
            ),
            pw.SizedBox(height: 20),

            // Scriptural Analysis
            pw.Text('SCRIPTURAL ANALYSIS', style: sectionTitleStyle),
            pw.SizedBox(height: 8),
            ...buildParagraphs(evaluation.statementAnalysis),
            pw.SizedBox(height: 20),

            // Key Scriptures
            pw.Text('KEY SCRIPTURES', style: sectionTitleStyle),
            pw.SizedBox(height: 8),
            ...evaluation.scriptures.map(
              (s) => pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    '${s.reference} (${s.supportsOrQualifies})',
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 13,
                    ),
                  ),
                  if (s.text.isNotEmpty) ...[
                    pw.SizedBox(height: 2),
                    pw.Text(
                      '"${PdfFormatter.cleanText(s.text)}"',
                      style: italicStyle,
                    ),
                  ],
                  pw.SizedBox(height: 4),
                  pw.Text(
                    PdfFormatter.cleanText(s.explanation),
                    style: bodyStyle,
                  ),
                  pw.SizedBox(height: 12),
                ],
              ),
            ),

            // Conclusion
            if (evaluation.conclusion.isNotEmpty) ...[
              pw.SizedBox(height: 10),
              pw.Text('CONCLUSION', style: sectionTitleStyle),
              pw.SizedBox(height: 8),
              ...buildParagraphs(evaluation.conclusion),
            ],

            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.SizedBox(height: 10),
            pw.Text(
              'Generated by illuminare Berean Check',
              style: labelStyle.copyWith(fontSize: 9, color: PdfColors.grey500),
            ),
          ];
        },
      ),
    );

    Directory? output;
    if (Platform.isAndroid) {
      output = Directory('/storage/emulated/0/Download');
    } else {
      output = await getDownloadsDirectory();
    }
    if (output == null || !output.existsSync()) {
      output = await getApplicationDocumentsDirectory();
    }

    final file = File(
      '${output.path}/berean_evaluation_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }
}
