import 'package:hive/hive.dart';
import '../models/exegesis_final_model.dart';

// ═══════════════════════════════════════════════════════════════════
//  HIVE TYPE ADAPTERS FOR FINAL EDITION MODELS
// ═══════════════════════════════════════════════════════════════════

/// Hive adapter for ExegesisLibraryItem
/// Stores the item as a map (id, type, source, subject, bigPicture, createdAt, resultJson)
class ExegesisLibraryItemAdapter extends TypeAdapter<ExegesisLibraryItem> {
  @override
  final int typeId = 117;

  @override
  ExegesisLibraryItem read(BinaryReader reader) {
    final map = reader.readMap().cast<String, dynamic>();
    return ExegesisLibraryItem.fromMap(map);
  }

  @override
  void write(BinaryWriter writer, ExegesisLibraryItem obj) {
    writer.writeMap(obj.toMap());
  }
}

/// Helper class to register all final edition Hive adapters
class ExegesisFinalHiveAdapters {
  static void registerAdapters() {
    // ExegesisEntryType and ExegesisSource adapters are generated by hive_generator
    if (!Hive.isAdapterRegistered(115)) {
      Hive.registerAdapter(ExegesisEntryTypeAdapter());
    }
    if (!Hive.isAdapterRegistered(116)) {
      Hive.registerAdapter(ExegesisSourceAdapter());
    }
    if (!Hive.isAdapterRegistered(117)) {
      Hive.registerAdapter(ExegesisLibraryItemAdapter());
    }
  }

  /// Opens the Hive box for final edition library items.
  /// Call this after [registerAdapters] during app init.
  static Future<Box<ExegesisLibraryItem>> openBox() async {
    return Hive.openBox<ExegesisLibraryItem>(boxName);
  }

  /// Box name for final edition exegesis library items
  static const String boxName = 'exegesis_final_library';
}
